<script lang="ts">
	import DualWheelGame from './DualWheelGame.svelte';
	import ThroneRoomBackdrop from '../../components/art/ThroneRoomBackdrop.svelte';
	const backgroundArt = new URL('../assets/bg-throne-room.png', import.meta.url).href;
	const slotSkinAtlas = new URL('../assets/slot-skin/ui_asset_vectorized.svg', import.meta.url).href;
</script>
<div class="throne-room-game-shell"><ThroneRoomBackdrop src={backgroundArt} /><div class="board-underlay board-underlay-frame" aria-hidden="true"><svg viewBox="733 0 545 621" preserveAspectRatio="xMidYMid meet"><use href={`${slotSkinAtlas}#frame`} /></svg></div><div class="board-underlay board-underlay-grid" aria-hidden="true"><svg viewBox="302 3 423 479" preserveAspectRatio="xMidYMid meet"><use href={`${slotSkinAtlas}#reel_grid`} /></svg></div><div class="hud-underlay" aria-hidden="true"><svg viewBox="11 604 572 118" preserveAspectRatio="xMidYMid meet"><use href={`${slotSkinAtlas}#control_bar`} /></svg></div><DualWheelGame /></div>
<style>
.throne-room-game-shell{position:relative;min-height:100vh;overflow:hidden;background:#040608;--scene-width:min(100vw,calc(100vh * 1.777));--scene-height:calc(var(--scene-width)/1.777);--scene-top:calc((100vh - var(--scene-height))*0.5);--board-width:calc(var(--scene-width)*0.4175);--grid-width:calc(var(--scene-width)*0.3200);--hud-width:calc(var(--scene-width)*0.4320);--hud-height:calc(var(--scene-height)*0.1586);--board-top:var(--scene-top);--grid-top:calc(var(--scene-top) + var(--scene-height)*0.1035);--hud-top:calc(var(--scene-top) + var(--scene-height)*0.8333)}
.board-underlay,.hud-underlay{position:absolute;left:50%;transform:translateX(-50%);pointer-events:none}.board-underlay svg,.hud-underlay svg{display:block;width:100%;height:auto}.board-underlay-frame{top:var(--board-top);width:var(--board-width);filter:drop-shadow(0 16px 28px rgba(0,0,0,.45))}.board-underlay-grid{top:var(--grid-top);width:var(--grid-width);filter:drop-shadow(0 8px 14px rgba(0,0,0,.26))}.hud-underlay{top:var(--hud-top);width:var(--hud-width);filter:drop-shadow(0 16px 24px rgba(0,0,0,.5))}
:global(.throne-room-game-shell .game-shell){background:transparent;min-height:100vh}:global(.throne-room-game-shell .theme-backdrop){display:none}:global(.throne-room-game-shell .game-stage){display:grid;place-items:center;padding:calc(var(--scene-top)+8px) 24px calc(var(--scene-top) + var(--scene-height)*0.22)}:global(.throne-room-game-shell .feature-banner){margin-inline:auto;width:min(640px,calc(100vw - 120px))}
:global(.throne-room-game-shell .board-frame){position:relative;z-index:1;padding:0!important;width:var(--board-width)!important;min-width:var(--board-width)!important;background:transparent!important;border:0!important;box-shadow:none!important}:global(.throne-room-game-shell .frame-velvet),:global(.throne-room-game-shell .frame-crown),:global(.throne-room-game-shell .frame-scroll){display:none!important}:global(.throne-room-game-shell .board){padding:0!important;background:transparent!important;box-shadow:none!important;transform:translateY(calc(var(--scene-height)*0.1035)) scale(.766);transform-origin:top center}:global(.throne-room-game-shell .board::before),:global(.throne-room-game-shell .board::after){display:none!important}:global(.throne-room-game-shell .cell){background:transparent!important;border:0!important;box-shadow:none!important}
:global(.throne-room-game-shell .symbol-art),:global(.throne-room-game-shell .symbol-art-sheet),:global(.throne-room-game-shell .wheel-tile-art),:global(.throne-room-game-shell .scatter-symbol){width:78px;height:78px}:global(.throne-room-game-shell .symbol-tile-shell),:global(.throne-room-game-shell .wheel-tile-shell),:global(.throne-room-game-shell .symbol-tile-shell-bonus){width:78px;height:78px}
:global(.throne-room-game-shell .top-bar){position:absolute;left:50%;top:var(--hud-top);width:var(--hud-width);height:var(--hud-height);transform:translateX(-50%);padding:0;border:0;background:transparent;backdrop-filter:none;pointer-events:none}:global(.throne-room-game-shell .top-bar-brand){display:none}:global(.throne-room-game-shell .top-bar-stats){position:absolute;inset:0;display:block}:global(.throne-room-game-shell .stat-pill){position:absolute;padding:0;border:0;background:transparent;box-shadow:none;text-align:center}:global(.throne-room-game-shell .stat-pill span){display:none}:global(.throne-room-game-shell .stat-pill strong){display:grid;place-items:center;height:100%;font-size:clamp(9px,.72vw,13px);font-weight:800;color:#f2f2f2;text-shadow:0 1px 2px rgba(0,0,0,.82)}:global(.throne-room-game-shell .top-bar-stats .stat-pill:nth-child(1)){left:5.3%;top:43.8%;width:26.4%;height:13.5%}:global(.throne-room-game-shell .top-bar-stats .stat-pill:nth-child(2)){left:58.7%;top:23.8%;width:13.7%;height:12.8%}:global(.throne-room-game-shell .top-bar-stats .stat-pill:nth-child(3)){left:55.8%;top:60.8%;width:22.8%;height:13.5%}
:global(.throne-room-game-shell .game-controls){position:absolute;left:50%;top:var(--hud-top);width:var(--hud-width);height:var(--hud-height);transform:translateX(-50%);padding:0;border:0;background:transparent;backdrop-filter:none;grid-template-columns:1fr;gap:0}:global(.throne-room-game-shell .controls-left),:global(.throne-room-game-shell .controls-center),:global(.throne-room-game-shell .controls-right){position:absolute;gap:0}:global(.throne-room-game-shell .controls-left){left:55.2%;top:19.2%;width:24.2%;height:17.6%}:global(.throne-room-game-shell .controls-center){left:40.85%;top:3.5%;width:10.95%;height:50.8%;transform:none;justify-items:center;margin-top:0}:global(.throne-room-game-shell .controls-right){left:84.8%;top:16.1%;width:12.9%;height:45.4%}:global(.throne-room-game-shell .bet-stepper){position:absolute;inset:0;display:block}:global(.throne-room-game-shell .bet-display){display:none}:global(.throne-room-game-shell .bet-stepper .ctrl-button:first-child){position:absolute;left:0;top:0;width:12.5%;height:100%;padding:0;border-radius:999px}:global(.throne-room-game-shell .bet-stepper .ctrl-button:last-child){position:absolute;right:0;top:0;width:12.5%;height:100%;padding:0;border-radius:999px}:global(.throne-room-game-shell .ctrl-button){padding:0;border:0;background:transparent;font-size:0;box-shadow:none}:global(.throne-room-game-shell .ctrl-button:hover:enabled){transform:none}:global(.throne-room-game-shell .bonus-buy-row){display:none}:global(.throne-room-game-shell .spin-button){width:100%;height:100%;margin-top:0;font-size:.72rem;box-shadow:none;border:0;background:radial-gradient(circle at 38% 28%,rgba(233,247,255,.96),rgba(171,222,255,.96) 34%,rgba(83,166,236,.98) 68%,rgba(33,99,174,.98) 100%)}:global(.throne-room-game-shell .spin-button-stop){background:linear-gradient(180deg,#ffc484,#f98f54 56%,#e55a2f 100%)}:global(.throne-room-game-shell .spin-button-skip){background:linear-gradient(180deg,#c2e8ff,#6fc4ff 56%,#37a2f5 100%)}:global(.throne-room-game-shell .status-text){display:none}:global(.throne-room-game-shell .toggle-row){position:absolute;inset:0;display:block}:global(.throne-room-game-shell .toggle-button){position:absolute;padding:0;background:transparent;border:0;border-radius:8px;font-size:0;color:transparent;line-height:0;box-shadow:none}:global(.throne-room-game-shell .toggle-button > *){font-size:0!important;color:transparent!important}:global(.throne-room-game-shell .toggle-row .toggle-button:first-child){left:18.5%;top:0;width:73.5%;height:34.5%}:global(.throne-room-game-shell .toggle-row .toggle-button:last-child){left:0;top:51.5%;width:100%;height:45%;margin-top:0}:global(.throne-room-game-shell .autoplay-select),:global(.throne-room-game-shell .autoplay-label),:global(.throne-room-game-shell .info-button){display:none}
@media (max-width:1200px){.throne-room-game-shell{--scene-width:min(100vw,calc(100vh * 1.72))}}@media (max-width:960px){.throne-room-game-shell{--scene-width:min(100vw,calc(100vh * 1.58))}}
</style>
